[package]
name = "zerod_types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
utoipa = { workspace = true }
strum = { workspace = true }
