apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "0d-master-api.fullname" . }}-data
  labels:
    {{- include "0d-master-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "10Gi" }}
  storageClassName: {{ .Values.persistence.storageClass | default "standard" }} 