{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "0d-master-api.serviceAccountName" . }}
  labels:
    {{- include "0d-master-api.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"  
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}