[package]
name = "zerod_bin"
version.workspace = true
edition.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
rust-version.workspace = true
exclude.workspace = true

[dependencies]
pragma-common.workspace = true
zerod_db.workspace = true
zerod_api.workspace = true
zerod_indexer.workspace = true
zerod_kpi.workspace = true
zerod_metrics.workspace = true

anyhow.workspace = true
clap.workspace = true
dotenvy.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
